### ISSUE TITLE
About pathRegion in "recursive splicing"

### ISSUE THREAD

**Issue by TsingYoo** [yuifu/Hayashi2018#3]
Hello, I'd like to know if the file "pathRegion" is generated by some procedures when processing the bam data, or downloaded from some specific website?
Thank you!

**Comment by yuifu** [comment]
@TsingYoo Hi!

I attached an example input for pathRegion.
[partial_novel.annotateWithReferenceIntron.noOverlapWithSmallerIntron.filterOutlierCells.sum.over5kbp.seesaw_p1.00e-05.raw.txt](https://github.com/yuifu/Hayashi2018/files/12300871/partial_novel.annotateWithReferenceIntron.noOverlapWithSmallerIntron.filterOutlierCells.sum.over5kbp.seesaw_p1.00e-05.raw.txt)

As written in  "Analysis of recursive splicing" subsection in Methods section in https://www.nature.com/articles/s41467-018-02866-0, we selected RS-site candidates with the following criteria:
(1) long (>150 kb) introns not overlapped with exons of any other
transcripts
(2) novel junctions with one anchor sequence corresponding to a known splicing boundary (“partially novel” by RSeQC)
(3) anchor sequences corresponding to intronic regions have pentamers found at 1% of all 5′ splice sites (GTAAG, GTGAG, GTAGG, GTATG, GTAAA, GTAAT, GTGGG, GTAAC, GTCAG, GTACG, GTACA, GTATT, GTACT, GTGTG, GTGCG, and GTACC) for 5′ splice sites or 3′ splice motif (polypyrimidine tract consisting of >11 pyrimidines present in the region of −22 to −1, including YAG as last three positions) for 3′ splice sites
(4) split alignment reads have >10-nt overhang
(5) >5-kb junction regions.

For (1) and (2):
1. Using junction_annotation.py in the RSeQC package, splice junctions in each BAM file were compared to reference gene model and classified into "Annotated", "Complete_novel", or "Partial_novel" categories.
2. We selected "partial_novel" splicing junctions.
3. Using awk and bedtools, we annotated the with "partial_novel" splicing junctions with long annotated introns (annotated introns (in GENCODE vM9 annotation) whose length is over 150 kb and did not overlap with smaller introns).

For (3):
Using a custom Julia script, we checked sequence features of anchors of splicing junctions.

For (4):
We counted, for each candidate RS site,  the number of split alignment reads have >10-nt overhang.

For (5):
We selected using R command.

Unfortunately, scripts for the above steps is not in the GitHub repository now, because Julia script is out-of-date (since there has been harsh updates in Julia lang) and need some modification in the currently available Julia version. Input files needed are BAM files and the reference gene annotation in BED12 format.
